version: '3'
services:
  star-wars-app:
    image: jmmoura/star-wars-api
    ports:
      - "8082:8080"
    depends_on:
      - star-wars-postgres
  star-wars-postgres:
    image: postgres:14
    user: postgres
    environment:
      - POSTGRES_DB=star-wars
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678